name: get_synced
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  get_it: ^3.1.0


  cupertino_icons: ^0.1.2
  http: ^0.12.0+4

  device_preview:

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true

  assets:
  - assets/images/
#  - assets/fonts:
#      - family: Schyler
#        fonts:
#          - asset: fonts/Schyler-Regular.ttf
#          - asset: fonts/Schyler-Italic.ttf
#            style: italic
#      - family: Trajan Pro
#        fonts:
#          - asset: fonts/TrajanPro.ttf
#          - asset: fonts/TrajanPro_Bold.ttf
#            weight: 700
